/**
 * eslint.config.js
 * ESLint flat config: finds bugs and dead code, nothing else. Layout is left
 * to Prettier (prettier.config.js), so the two tools never argue about a line.
 *
 * Every file is an ES module. What differs between the parts of the project is
 * the runtime, and with it the globals a file may use without importing them:
 * the client sees `document` and `window`, the server `process`, the tests
 * Jest's `describe`/`test`/`expect`. Naming them per folder turns a global that
 * does not exist where the file runs into a lint error instead of a crash.
 */

import js from '@eslint/js';
import globals from 'globals';

export default [
  // Generated by `npm test -- --coverage`, never committed.
  { ignores: ['coverage/'] },

  js.configs.recommended,

  // The browser client.
  {
    files: ['public/js/**/*.js'],
    languageOptions: { globals: globals.browser }
  },

  // The rule module runs in the browser *and* on the server, so it may only
  // use what both of them provide.
  {
    files: ['shared/**/*.js'],
    languageOptions: { globals: globals['shared-node-browser'] }
  },

  // Server, its libraries, the tooling and these config files.
  {
    files: ['server.js', 'lib/**/*.js', 'scripts/**/*.js', '*.config.js'],
    languageOptions: { globals: globals.node }
  },

  // Jest runs the tests in Node and provides describe/test/expect as globals.
  {
    files: ['tests/**/*.js'],
    languageOptions: { globals: { ...globals.node, ...globals.jest } }
  },

  // Beyond the recommended set: the review criteria ask for const/let only
  // and for comparisons that do not convert types behind the reader's back.
  {
    rules: {
      'no-var': 'error',
      'prefer-const': 'error',
      'eqeqeq': 'error'
    }
  }
];
